Tic Tac Toe Javascript project
hillarioh/TIC-TAC-TOE-JS pull request #1
Opened 2020-07-28 09:49 UTC by hillarioh

Hi, this is our submission for code review of the tic tac toe javascript project. It entails 
- Form inputs
- Objects (Player and Board)
- Dom elements

We are looking forward to your review, Thanks

2020-07-28 21:34 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

**Important Notice:** Don't let us forget the goal of this project, we need to make use of `Factory Functions` and `The Module Pattern` 
![image](https://user-images.githubusercontent.com/31897434/88719600-737b3d00-d11b-11ea-82fe-f8eb980b913c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623090/

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-28 21:34 UTC, bellom commented on Js/index.js
> +];
I think all these can be called global variables right?
In the `Odin` instructions, you have been told to minimize the global variables in this project.
Note: Once you make use of `Factory Functions` and `The Module Pattern` you don't need to have any global variables in your code.

![image](https://user-images.githubusercontent.com/31897434/88721399-4ed49480-d11e-11ea-940f-93cb24c62cfb.png)

2020-07-28 21:34 UTC, bellom commented on Js/index.js
> +
According to the instructions from `Odin` you are supposed to have the following classes `game`, `player`, and `gameboard`, don't forget to make use of factory functions.
![image](https://user-images.githubusercontent.com/31897434/88722986-04ecae00-d120-11ea-8b56-202c4ff7f05e.png)
https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript

2020-07-28 21:34 UTC, bellom commented on Js/index.js
> +
Let's separate the DOM from application logic, you can create another file for DOM.

![image](https://user-images.githubusercontent.com/31897434/73420341-70e18b80-4322-11ea-840a-fa14e04b592b.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/

2020-07-29 19:39 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

- [ ] `OPTIONAL:` Your game should show when it's a draw.

_Good luck with your future projects and happy coding!_ 🎉

2020-07-30 18:59 UTC, merged